//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KanbanModel", "FK_USUARIOSxBOARD_BOARDS", "BOARDS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.BOARD), "USUARIOSxBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.USUARIOSxBOARD), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "FK_CARDS_PRIORIDADES", "PRIORIDADES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.PRIORIDADE), "CARDS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.CARD), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "FK_CARDS_TIPO", "TIPO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.TIPO), "CARDS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.CARD), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "FK_CARDSxUSUARIOS_CARDS", "CARDS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.CARD), "CARDSxUSUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.CARDSxUSUARIO), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "FK_USUARIOSxBOARD_ROLE", "ROLE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.ROLE), "USUARIOSxBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.USUARIOSxBOARD), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "FK_USUARIOSxBOARD_USUARIOS", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kanban_board_project.App_Data.USUARIO), "USUARIOSxBOARD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.USUARIOSxBOARD), true)]
[assembly: EdmRelationshipAttribute("KanbanModel", "CARDSxCOLUMNAS", "CARDS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.CARD), "COLUMNA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kanban_board_project.App_Data.COLUMNA))]

#endregion

namespace Kanban_board_project.App_Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KanbanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KanbanEntities object using the connection string found in the 'KanbanEntities' section of the application configuration file.
        /// </summary>
        public KanbanEntities() : base("name=KanbanEntities", "KanbanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KanbanEntities object.
        /// </summary>
        public KanbanEntities(string connectionString) : base(connectionString, "KanbanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KanbanEntities object.
        /// </summary>
        public KanbanEntities(EntityConnection connection) : base(connection, "KanbanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BOARD> BOARDS
        {
            get
            {
                if ((_BOARDS == null))
                {
                    _BOARDS = base.CreateObjectSet<BOARD>("BOARDS");
                }
                return _BOARDS;
            }
        }
        private ObjectSet<BOARD> _BOARDS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CARD> CARDS
        {
            get
            {
                if ((_CARDS == null))
                {
                    _CARDS = base.CreateObjectSet<CARD>("CARDS");
                }
                return _CARDS;
            }
        }
        private ObjectSet<CARD> _CARDS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CARDSxUSUARIO> CARDSxUSUARIOS
        {
            get
            {
                if ((_CARDSxUSUARIOS == null))
                {
                    _CARDSxUSUARIOS = base.CreateObjectSet<CARDSxUSUARIO>("CARDSxUSUARIOS");
                }
                return _CARDSxUSUARIOS;
            }
        }
        private ObjectSet<CARDSxUSUARIO> _CARDSxUSUARIOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COLUMNA> COLUMNAs
        {
            get
            {
                if ((_COLUMNAs == null))
                {
                    _COLUMNAs = base.CreateObjectSet<COLUMNA>("COLUMNAs");
                }
                return _COLUMNAs;
            }
        }
        private ObjectSet<COLUMNA> _COLUMNAs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRIORIDADE> PRIORIDADES
        {
            get
            {
                if ((_PRIORIDADES == null))
                {
                    _PRIORIDADES = base.CreateObjectSet<PRIORIDADE>("PRIORIDADES");
                }
                return _PRIORIDADES;
            }
        }
        private ObjectSet<PRIORIDADE> _PRIORIDADES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ROLE> ROLEs
        {
            get
            {
                if ((_ROLEs == null))
                {
                    _ROLEs = base.CreateObjectSet<ROLE>("ROLEs");
                }
                return _ROLEs;
            }
        }
        private ObjectSet<ROLE> _ROLEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TIPO> TIPOes
        {
            get
            {
                if ((_TIPOes == null))
                {
                    _TIPOes = base.CreateObjectSet<TIPO>("TIPOes");
                }
                return _TIPOes;
            }
        }
        private ObjectSet<TIPO> _TIPOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIO> USUARIOS
        {
            get
            {
                if ((_USUARIOS == null))
                {
                    _USUARIOS = base.CreateObjectSet<USUARIO>("USUARIOS");
                }
                return _USUARIOS;
            }
        }
        private ObjectSet<USUARIO> _USUARIOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIOSxBOARD> USUARIOSxBOARDs
        {
            get
            {
                if ((_USUARIOSxBOARDs == null))
                {
                    _USUARIOSxBOARDs = base.CreateObjectSet<USUARIOSxBOARD>("USUARIOSxBOARDs");
                }
                return _USUARIOSxBOARDs;
            }
        }
        private ObjectSet<USUARIOSxBOARD> _USUARIOSxBOARDs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BOARDS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBOARDS(BOARD bOARD)
        {
            base.AddObject("BOARDS", bOARD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CARDS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCARDS(CARD cARD)
        {
            base.AddObject("CARDS", cARD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CARDSxUSUARIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCARDSxUSUARIOS(CARDSxUSUARIO cARDSxUSUARIO)
        {
            base.AddObject("CARDSxUSUARIOS", cARDSxUSUARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COLUMNAs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOLUMNAs(COLUMNA cOLUMNA)
        {
            base.AddObject("COLUMNAs", cOLUMNA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRIORIDADES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRIORIDADES(PRIORIDADE pRIORIDADE)
        {
            base.AddObject("PRIORIDADES", pRIORIDADE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ROLEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToROLEs(ROLE rOLE)
        {
            base.AddObject("ROLEs", rOLE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TIPOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTIPOes(TIPO tIPO)
        {
            base.AddObject("TIPOes", tIPO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOS(USUARIO uSUARIO)
        {
            base.AddObject("USUARIOS", uSUARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOSxBOARDs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOSxBOARDs(USUARIOSxBOARD uSUARIOSxBOARD)
        {
            base.AddObject("USUARIOSxBOARDs", uSUARIOSxBOARD);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="BOARD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BOARD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BOARD object.
        /// </summary>
        /// <param name="iDBOARD">Initial value of the IDBOARD property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        /// <param name="cOLUMNAS">Initial value of the COLUMNAS property.</param>
        public static BOARD CreateBOARD(global::System.Int32 iDBOARD, global::System.String nOMBRE, global::System.Int32 cOLUMNAS)
        {
            BOARD bOARD = new BOARD();
            bOARD.IDBOARD = iDBOARD;
            bOARD.NOMBRE = nOMBRE;
            bOARD.COLUMNAS = cOLUMNAS;
            return bOARD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDBOARD
        {
            get
            {
                return _IDBOARD;
            }
            set
            {
                if (_IDBOARD != value)
                {
                    OnIDBOARDChanging(value);
                    ReportPropertyChanging("IDBOARD");
                    _IDBOARD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDBOARD");
                    OnIDBOARDChanged();
                }
            }
        }
        private global::System.Int32 _IDBOARD;
        partial void OnIDBOARDChanging(global::System.Int32 value);
        partial void OnIDBOARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FECHAINICIO
        {
            get
            {
                return _FECHAINICIO;
            }
            set
            {
                OnFECHAINICIOChanging(value);
                ReportPropertyChanging("FECHAINICIO");
                _FECHAINICIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FECHAINICIO");
                OnFECHAINICIOChanged();
            }
        }
        private global::System.String _FECHAINICIO;
        partial void OnFECHAINICIOChanging(global::System.String value);
        partial void OnFECHAINICIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 COLUMNAS
        {
            get
            {
                return _COLUMNAS;
            }
            set
            {
                OnCOLUMNASChanging(value);
                ReportPropertyChanging("COLUMNAS");
                _COLUMNAS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COLUMNAS");
                OnCOLUMNASChanged();
            }
        }
        private global::System.Int32 _COLUMNAS;
        partial void OnCOLUMNASChanging(global::System.Int32 value);
        partial void OnCOLUMNASChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_BOARDS", "USUARIOSxBOARD")]
        public EntityCollection<USUARIOSxBOARD> USUARIOSxBOARDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "USUARIOSxBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "USUARIOSxBOARD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="CARD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CARD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CARD object.
        /// </summary>
        /// <param name="iDCARD">Initial value of the IDCARD property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        /// <param name="fECHAINICIO">Initial value of the FECHAINICIO property.</param>
        /// <param name="fECHAFINAL">Initial value of the FECHAFINAL property.</param>
        /// <param name="cOLOR">Initial value of the COLOR property.</param>
        /// <param name="pRIORIDAD">Initial value of the PRIORIDAD property.</param>
        /// <param name="tIPO">Initial value of the TIPO property.</param>
        public static CARD CreateCARD(global::System.Int32 iDCARD, global::System.String nOMBRE, global::System.String fECHAINICIO, global::System.String fECHAFINAL, global::System.String cOLOR, global::System.Int32 pRIORIDAD, global::System.Int32 tIPO)
        {
            CARD cARD = new CARD();
            cARD.IDCARD = iDCARD;
            cARD.NOMBRE = nOMBRE;
            cARD.FECHAINICIO = fECHAINICIO;
            cARD.FECHAFINAL = fECHAFINAL;
            cARD.COLOR = cOLOR;
            cARD.PRIORIDAD = pRIORIDAD;
            cARD.TIPO = tIPO;
            return cARD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCARD
        {
            get
            {
                return _IDCARD;
            }
            set
            {
                if (_IDCARD != value)
                {
                    OnIDCARDChanging(value);
                    ReportPropertyChanging("IDCARD");
                    _IDCARD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCARD");
                    OnIDCARDChanged();
                }
            }
        }
        private global::System.Int32 _IDCARD;
        partial void OnIDCARDChanging(global::System.Int32 value);
        partial void OnIDCARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FECHAINICIO
        {
            get
            {
                return _FECHAINICIO;
            }
            set
            {
                OnFECHAINICIOChanging(value);
                ReportPropertyChanging("FECHAINICIO");
                _FECHAINICIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FECHAINICIO");
                OnFECHAINICIOChanged();
            }
        }
        private global::System.String _FECHAINICIO;
        partial void OnFECHAINICIOChanging(global::System.String value);
        partial void OnFECHAINICIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FECHAFINAL
        {
            get
            {
                return _FECHAFINAL;
            }
            set
            {
                OnFECHAFINALChanging(value);
                ReportPropertyChanging("FECHAFINAL");
                _FECHAFINAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FECHAFINAL");
                OnFECHAFINALChanged();
            }
        }
        private global::System.String _FECHAFINAL;
        partial void OnFECHAFINALChanging(global::System.String value);
        partial void OnFECHAFINALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COLOR
        {
            get
            {
                return _COLOR;
            }
            set
            {
                OnCOLORChanging(value);
                ReportPropertyChanging("COLOR");
                _COLOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("COLOR");
                OnCOLORChanged();
            }
        }
        private global::System.String _COLOR;
        partial void OnCOLORChanging(global::System.String value);
        partial void OnCOLORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRIORIDAD
        {
            get
            {
                return _PRIORIDAD;
            }
            set
            {
                OnPRIORIDADChanging(value);
                ReportPropertyChanging("PRIORIDAD");
                _PRIORIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRIORIDAD");
                OnPRIORIDADChanged();
            }
        }
        private global::System.Int32 _PRIORIDAD;
        partial void OnPRIORIDADChanging(global::System.Int32 value);
        partial void OnPRIORIDADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.Int32 _TIPO;
        partial void OnTIPOChanging(global::System.Int32 value);
        partial void OnTIPOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDS_PRIORIDADES", "PRIORIDADES")]
        public PRIORIDADE PRIORIDADE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRIORIDADE>("KanbanModel.FK_CARDS_PRIORIDADES", "PRIORIDADES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRIORIDADE>("KanbanModel.FK_CARDS_PRIORIDADES", "PRIORIDADES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRIORIDADE> PRIORIDADEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRIORIDADE>("KanbanModel.FK_CARDS_PRIORIDADES", "PRIORIDADES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRIORIDADE>("KanbanModel.FK_CARDS_PRIORIDADES", "PRIORIDADES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDS_TIPO", "TIPO")]
        public TIPO TIPO1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO>("KanbanModel.FK_CARDS_TIPO", "TIPO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO>("KanbanModel.FK_CARDS_TIPO", "TIPO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TIPO> TIPO1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO>("KanbanModel.FK_CARDS_TIPO", "TIPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TIPO>("KanbanModel.FK_CARDS_TIPO", "TIPO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDSxUSUARIOS_CARDS", "CARDSxUSUARIOS")]
        public EntityCollection<CARDSxUSUARIO> CARDSxUSUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CARDSxUSUARIO>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDSxUSUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CARDSxUSUARIO>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDSxUSUARIOS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "CARDSxCOLUMNAS", "COLUMNA")]
        public EntityCollection<COLUMNA> COLUMNAs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COLUMNA>("KanbanModel.CARDSxCOLUMNAS", "COLUMNA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COLUMNA>("KanbanModel.CARDSxCOLUMNAS", "COLUMNA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="CARDSxUSUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CARDSxUSUARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CARDSxUSUARIO object.
        /// </summary>
        /// <param name="iDCARD">Initial value of the IDCARD property.</param>
        /// <param name="iDUSUARIO">Initial value of the IDUSUARIO property.</param>
        public static CARDSxUSUARIO CreateCARDSxUSUARIO(global::System.Int32 iDCARD, global::System.Int32 iDUSUARIO)
        {
            CARDSxUSUARIO cARDSxUSUARIO = new CARDSxUSUARIO();
            cARDSxUSUARIO.IDCARD = iDCARD;
            cARDSxUSUARIO.IDUSUARIO = iDUSUARIO;
            return cARDSxUSUARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCARD
        {
            get
            {
                return _IDCARD;
            }
            set
            {
                if (_IDCARD != value)
                {
                    OnIDCARDChanging(value);
                    ReportPropertyChanging("IDCARD");
                    _IDCARD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCARD");
                    OnIDCARDChanged();
                }
            }
        }
        private global::System.Int32 _IDCARD;
        partial void OnIDCARDChanging(global::System.Int32 value);
        partial void OnIDCARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIO
        {
            get
            {
                return _IDUSUARIO;
            }
            set
            {
                if (_IDUSUARIO != value)
                {
                    OnIDUSUARIOChanging(value);
                    ReportPropertyChanging("IDUSUARIO");
                    _IDUSUARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIO");
                    OnIDUSUARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIO;
        partial void OnIDUSUARIOChanging(global::System.Int32 value);
        partial void OnIDUSUARIOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDSxUSUARIOS_CARDS", "CARDS")]
        public CARD CARD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CARD>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CARD>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CARD> CARDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CARD>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CARD>("KanbanModel.FK_CARDSxUSUARIOS_CARDS", "CARDS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="COLUMNA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COLUMNA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COLUMNA object.
        /// </summary>
        /// <param name="iDCOLUMNA">Initial value of the IDCOLUMNA property.</param>
        /// <param name="iDBOARD">Initial value of the IDBOARD property.</param>
        /// <param name="pOSICION">Initial value of the POSICION property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        /// <param name="wHIPLIMITE">Initial value of the WHIPLIMITE property.</param>
        public static COLUMNA CreateCOLUMNA(global::System.Int32 iDCOLUMNA, global::System.Int32 iDBOARD, global::System.Int32 pOSICION, global::System.String nOMBRE, global::System.Int32 wHIPLIMITE)
        {
            COLUMNA cOLUMNA = new COLUMNA();
            cOLUMNA.IDCOLUMNA = iDCOLUMNA;
            cOLUMNA.IDBOARD = iDBOARD;
            cOLUMNA.POSICION = pOSICION;
            cOLUMNA.NOMBRE = nOMBRE;
            cOLUMNA.WHIPLIMITE = wHIPLIMITE;
            return cOLUMNA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCOLUMNA
        {
            get
            {
                return _IDCOLUMNA;
            }
            set
            {
                if (_IDCOLUMNA != value)
                {
                    OnIDCOLUMNAChanging(value);
                    ReportPropertyChanging("IDCOLUMNA");
                    _IDCOLUMNA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCOLUMNA");
                    OnIDCOLUMNAChanged();
                }
            }
        }
        private global::System.Int32 _IDCOLUMNA;
        partial void OnIDCOLUMNAChanging(global::System.Int32 value);
        partial void OnIDCOLUMNAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDBOARD
        {
            get
            {
                return _IDBOARD;
            }
            set
            {
                OnIDBOARDChanging(value);
                ReportPropertyChanging("IDBOARD");
                _IDBOARD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDBOARD");
                OnIDBOARDChanged();
            }
        }
        private global::System.Int32 _IDBOARD;
        partial void OnIDBOARDChanging(global::System.Int32 value);
        partial void OnIDBOARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 POSICION
        {
            get
            {
                return _POSICION;
            }
            set
            {
                OnPOSICIONChanging(value);
                ReportPropertyChanging("POSICION");
                _POSICION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POSICION");
                OnPOSICIONChanged();
            }
        }
        private global::System.Int32 _POSICION;
        partial void OnPOSICIONChanging(global::System.Int32 value);
        partial void OnPOSICIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WHIPLIMITE
        {
            get
            {
                return _WHIPLIMITE;
            }
            set
            {
                OnWHIPLIMITEChanging(value);
                ReportPropertyChanging("WHIPLIMITE");
                _WHIPLIMITE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WHIPLIMITE");
                OnWHIPLIMITEChanged();
            }
        }
        private global::System.Int32 _WHIPLIMITE;
        partial void OnWHIPLIMITEChanging(global::System.Int32 value);
        partial void OnWHIPLIMITEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "CARDSxCOLUMNAS", "CARDS")]
        public EntityCollection<CARD> CARDS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CARD>("KanbanModel.CARDSxCOLUMNAS", "CARDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CARD>("KanbanModel.CARDSxCOLUMNAS", "CARDS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="PRIORIDADE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRIORIDADE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRIORIDADE object.
        /// </summary>
        /// <param name="iDPRIORIDADES">Initial value of the IDPRIORIDADES property.</param>
        public static PRIORIDADE CreatePRIORIDADE(global::System.Int32 iDPRIORIDADES)
        {
            PRIORIDADE pRIORIDADE = new PRIORIDADE();
            pRIORIDADE.IDPRIORIDADES = iDPRIORIDADES;
            return pRIORIDADE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPRIORIDADES
        {
            get
            {
                return _IDPRIORIDADES;
            }
            set
            {
                if (_IDPRIORIDADES != value)
                {
                    OnIDPRIORIDADESChanging(value);
                    ReportPropertyChanging("IDPRIORIDADES");
                    _IDPRIORIDADES = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPRIORIDADES");
                    OnIDPRIORIDADESChanged();
                }
            }
        }
        private global::System.Int32 _IDPRIORIDADES;
        partial void OnIDPRIORIDADESChanging(global::System.Int32 value);
        partial void OnIDPRIORIDADESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIORIDAD
        {
            get
            {
                return _PRIORIDAD;
            }
            set
            {
                OnPRIORIDADChanging(value);
                ReportPropertyChanging("PRIORIDAD");
                _PRIORIDAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIORIDAD");
                OnPRIORIDADChanged();
            }
        }
        private global::System.String _PRIORIDAD;
        partial void OnPRIORIDADChanging(global::System.String value);
        partial void OnPRIORIDADChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDS_PRIORIDADES", "CARDS")]
        public EntityCollection<CARD> CARDS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CARD>("KanbanModel.FK_CARDS_PRIORIDADES", "CARDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CARD>("KanbanModel.FK_CARDS_PRIORIDADES", "CARDS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="ROLE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ROLE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ROLE object.
        /// </summary>
        /// <param name="iDROLE">Initial value of the IDROLE property.</param>
        /// <param name="rOLE1">Initial value of the ROLE1 property.</param>
        public static ROLE CreateROLE(global::System.Int32 iDROLE, global::System.String rOLE1)
        {
            ROLE rOLE = new ROLE();
            rOLE.IDROLE = iDROLE;
            rOLE.ROLE1 = rOLE1;
            return rOLE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDROLE
        {
            get
            {
                return _IDROLE;
            }
            set
            {
                if (_IDROLE != value)
                {
                    OnIDROLEChanging(value);
                    ReportPropertyChanging("IDROLE");
                    _IDROLE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDROLE");
                    OnIDROLEChanged();
                }
            }
        }
        private global::System.Int32 _IDROLE;
        partial void OnIDROLEChanging(global::System.Int32 value);
        partial void OnIDROLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ROLE1
        {
            get
            {
                return _ROLE1;
            }
            set
            {
                OnROLE1Changing(value);
                ReportPropertyChanging("ROLE1");
                _ROLE1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ROLE1");
                OnROLE1Changed();
            }
        }
        private global::System.String _ROLE1;
        partial void OnROLE1Changing(global::System.String value);
        partial void OnROLE1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_ROLE", "USUARIOSxBOARD")]
        public EntityCollection<USUARIOSxBOARD> USUARIOSxBOARDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "USUARIOSxBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "USUARIOSxBOARD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="TIPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIPO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TIPO object.
        /// </summary>
        /// <param name="iDTIPOS">Initial value of the IDTIPOS property.</param>
        /// <param name="tIPO1">Initial value of the TIPO1 property.</param>
        public static TIPO CreateTIPO(global::System.Int32 iDTIPOS, global::System.String tIPO1)
        {
            TIPO tIPO = new TIPO();
            tIPO.IDTIPOS = iDTIPOS;
            tIPO.TIPO1 = tIPO1;
            return tIPO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDTIPOS
        {
            get
            {
                return _IDTIPOS;
            }
            set
            {
                if (_IDTIPOS != value)
                {
                    OnIDTIPOSChanging(value);
                    ReportPropertyChanging("IDTIPOS");
                    _IDTIPOS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDTIPOS");
                    OnIDTIPOSChanged();
                }
            }
        }
        private global::System.Int32 _IDTIPOS;
        partial void OnIDTIPOSChanging(global::System.Int32 value);
        partial void OnIDTIPOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO1
        {
            get
            {
                return _TIPO1;
            }
            set
            {
                OnTIPO1Changing(value);
                ReportPropertyChanging("TIPO1");
                _TIPO1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO1");
                OnTIPO1Changed();
            }
        }
        private global::System.String _TIPO1;
        partial void OnTIPO1Changing(global::System.String value);
        partial void OnTIPO1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_CARDS_TIPO", "CARDS")]
        public EntityCollection<CARD> CARDS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CARD>("KanbanModel.FK_CARDS_TIPO", "CARDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CARD>("KanbanModel.FK_CARDS_TIPO", "CARDS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIO object.
        /// </summary>
        /// <param name="iDUSUARIO">Initial value of the IDUSUARIO property.</param>
        public static USUARIO CreateUSUARIO(global::System.Int32 iDUSUARIO)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.IDUSUARIO = iDUSUARIO;
            return uSUARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIO
        {
            get
            {
                return _IDUSUARIO;
            }
            set
            {
                if (_IDUSUARIO != value)
                {
                    OnIDUSUARIOChanging(value);
                    ReportPropertyChanging("IDUSUARIO");
                    _IDUSUARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIO");
                    OnIDUSUARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIO;
        partial void OnIDUSUARIOChanging(global::System.Int32 value);
        partial void OnIDUSUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROFECION
        {
            get
            {
                return _PROFECION;
            }
            set
            {
                OnPROFECIONChanging(value);
                ReportPropertyChanging("PROFECION");
                _PROFECION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROFECION");
                OnPROFECIONChanged();
            }
        }
        private global::System.String _PROFECION;
        partial void OnPROFECIONChanging(global::System.String value);
        partial void OnPROFECIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PICTURE
        {
            get
            {
                return StructuralObject.GetValidValue(_PICTURE);
            }
            set
            {
                OnPICTUREChanging(value);
                ReportPropertyChanging("PICTURE");
                _PICTURE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PICTURE");
                OnPICTUREChanged();
            }
        }
        private global::System.Byte[] _PICTURE;
        partial void OnPICTUREChanging(global::System.Byte[] value);
        partial void OnPICTUREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO1
        {
            get
            {
                return _USUARIO1;
            }
            set
            {
                OnUSUARIO1Changing(value);
                ReportPropertyChanging("USUARIO1");
                _USUARIO1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO1");
                OnUSUARIO1Changed();
            }
        }
        private global::System.String _USUARIO1;
        partial void OnUSUARIO1Changing(global::System.String value);
        partial void OnUSUARIO1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CORREO
        {
            get
            {
                return _CORREO;
            }
            set
            {
                OnCORREOChanging(value);
                ReportPropertyChanging("CORREO");
                _CORREO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CORREO");
                OnCORREOChanged();
            }
        }
        private global::System.String _CORREO;
        partial void OnCORREOChanging(global::System.String value);
        partial void OnCORREOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_USUARIOS", "USUARIOSxBOARD")]
        public EntityCollection<USUARIOSxBOARD> USUARIOSxBOARDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOSxBOARD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOSxBOARD>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOSxBOARD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanbanModel", Name="USUARIOSxBOARD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOSxBOARD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIOSxBOARD object.
        /// </summary>
        /// <param name="iDUSUARIO">Initial value of the IDUSUARIO property.</param>
        /// <param name="iDBOARD">Initial value of the IDBOARD property.</param>
        /// <param name="rOLE">Initial value of the ROLE property.</param>
        public static USUARIOSxBOARD CreateUSUARIOSxBOARD(global::System.Int32 iDUSUARIO, global::System.Int32 iDBOARD, global::System.Int32 rOLE)
        {
            USUARIOSxBOARD uSUARIOSxBOARD = new USUARIOSxBOARD();
            uSUARIOSxBOARD.IDUSUARIO = iDUSUARIO;
            uSUARIOSxBOARD.IDBOARD = iDBOARD;
            uSUARIOSxBOARD.ROLE = rOLE;
            return uSUARIOSxBOARD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIO
        {
            get
            {
                return _IDUSUARIO;
            }
            set
            {
                if (_IDUSUARIO != value)
                {
                    OnIDUSUARIOChanging(value);
                    ReportPropertyChanging("IDUSUARIO");
                    _IDUSUARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIO");
                    OnIDUSUARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIO;
        partial void OnIDUSUARIOChanging(global::System.Int32 value);
        partial void OnIDUSUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDBOARD
        {
            get
            {
                return _IDBOARD;
            }
            set
            {
                if (_IDBOARD != value)
                {
                    OnIDBOARDChanging(value);
                    ReportPropertyChanging("IDBOARD");
                    _IDBOARD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDBOARD");
                    OnIDBOARDChanged();
                }
            }
        }
        private global::System.Int32 _IDBOARD;
        partial void OnIDBOARDChanging(global::System.Int32 value);
        partial void OnIDBOARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ROLE
        {
            get
            {
                return _ROLE;
            }
            set
            {
                if (_ROLE != value)
                {
                    OnROLEChanging(value);
                    ReportPropertyChanging("ROLE");
                    _ROLE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ROLE");
                    OnROLEChanged();
                }
            }
        }
        private global::System.Int32 _ROLE;
        partial void OnROLEChanging(global::System.Int32 value);
        partial void OnROLEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_BOARDS", "BOARDS")]
        public BOARD BOARD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "BOARDS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "BOARDS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BOARD> BOARDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "BOARDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BOARD>("KanbanModel.FK_USUARIOSxBOARD_BOARDS", "BOARDS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_ROLE", "ROLE")]
        public ROLE ROLE1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLE>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "ROLE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLE>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "ROLE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ROLE> ROLE1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLE>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "ROLE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ROLE>("KanbanModel.FK_USUARIOSxBOARD_ROLE", "ROLE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanbanModel", "FK_USUARIOSxBOARD_USUARIOS", "USUARIOS")]
        public USUARIO USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIO> USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIO>("KanbanModel.FK_USUARIOSxBOARD_USUARIOS", "USUARIOS", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
